version: '3'
name: 'Dokcer_KT'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.pgsql
    volumes:
      - psql_volume:/var/lib/postgresql/data
    networks:
      - fast_api

  pgadmin:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    networks:
      - fast_api
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
volumes:
  pgadmin_volume:
  psql_volume:
networks:
  fast_api:
